---
apiVersion: v1
kind: Service
metadata:
  name: api-price-service
  labels:
    app: api-price-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  externalIPs:
  - 192.168.1.2
  externalTrafficPolicy: Cluster
  selector:
    app: api-price
  type: LoadBalancer


