version: '3.4'
services:
  api:
    build: 
      context: .
    container_name: api_price
    environment:
     - RUST_LOG=info
     - TICKER=ACMFT|ACORDO01|ASRFT|ATMFT|BCH|BTC|CAIFT|CHZ|ETH|GALFT|IMOB01|JUVFT|LINK|LTC|MBCONS01|MBCONS02|MBFP01|MBFP02|MBPRK01|MBPRK02|MBPRK03|MBPRK04|MBVASCO01|MCO2|OGFT|PAXG|PSGFT|USDC|WBX|XRP
    ports: 
     - 8080:8080     
      
#limit 32,760 char