name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: rust:1.50-slim

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo check --verbose
    #- name: Run tests
    #  run: cargo test --verbose
